# docker-compose.yml
version: "3.8"

services:
  flo_robot:
    build:
      context: .
      dockerfile: Dockerfile
    image: flo_system_v2_game_demo:latest
    container_name: flo_game
    network_mode: host               # ROS networking on host
    environment:
      - DISPLAY=${DISPLAY}           # forward X11
      - XAUTHORITY=/home/${USER}/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY}:/home/${USER}/.Xauthority:ro
      - /dev:/dev                     # for camera & devices
      - ./certs/aws-credentials:/root/.aws/credentials:ro
      - ./certs/aws-config:/root/.aws/config:ro
    devices:
      - /dev/video0:/dev/video0      # adjust if your Astra camera is on a different node
    working_dir: /catkin_ws
    command: >
      bash -lc "
        source /opt/ros/noetic/setup.bash &&
        source /catkin_ws/devel/setup.bash
        # Add commands to launch your ROS nodes or applications here
      "
