#!/usr/bin/env python3
"""Generate FLO udev rules from connected device nodes.

Run this on the Linux host, not inside Docker. Example:

    python3 utility/create_udev_rules.py \
        --camera /dev/video0 \
        --motors /dev/ttyUSB0 \
        --face /dev/ttyACM0 \
        -o 99-flo-devices.rules

Install directly to udev on the host:

sudo python3 utility/create_udev_rules.py \
  --camera /dev/video0 \
  --motors /dev/ttyUSB0 \
  --face /dev/ttyACM0 \
  -o /etc/udev/rules.d/99-flo-devices.rules


Then reload udev:

sudo udevadm control --reload-rules
sudo udevadm trigger

Then confirm:

ls -l /dev/flo_camera /dev/flo_motors /dev/flo_face

"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

HEADER = [
    "# FLO device rules",
    "# Generated by utility/create_udev_rules.py",
    "# Install on the Linux host under /etc/udev/rules.d/ and reload udev.",
    "",
]

DEFAULT_OUTPUT = Path("99-flo-devices.rules")


@dataclass(frozen=True)
class DeviceSpec:
    label: str
    symlink: str
    subsystem: str
    devnode: Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate udev rules for FLO camera and serial devices."
    )
    parser.add_argument(
        "--camera",
        type=Path,
        help="Current camera device node, for example /dev/video0.",
    )
    parser.add_argument(
        "--motors",
        type=Path,
        help="Current motor controller device node, for example /dev/ttyUSB0.",
    )
    parser.add_argument(
        "--face",
        type=Path,
        help="Current face device node, for example /dev/ttyACM0.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help=(
            "Write rules to this path instead of stdout. "
            f"Use {DEFAULT_OUTPUT} for a local review file."
        ),
    )
    return parser.parse_args()


def iter_specs(args: argparse.Namespace) -> Iterable[DeviceSpec]:
    candidates = [
        ("camera", "flo_camera", "video4linux", args.camera),
        ("motors", "flo_motors", "tty", args.motors),
        ("face", "flo_face", "tty", args.face),
    ]
    for label, symlink, subsystem, devnode in candidates:
        if devnode is not None:
            yield DeviceSpec(label, symlink, subsystem, devnode)


def query_udev_properties(devnode: Path) -> Dict[str, str]:
    if not devnode.exists():
        raise FileNotFoundError(f"Device does not exist: {devnode}")

    result = subprocess.run(
        ["udevadm", "info", "--query=property", f"--name={devnode}"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip() or "unknown error"
        raise RuntimeError(f"udevadm failed for {devnode}: {message}")

    properties: Dict[str, str] = {}
    for line in result.stdout.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        properties[key] = value
    return properties


def query_sysfs_attributes(devnode: Path) -> Dict[str, str]:
    """Read useful sysfs attributes for the device when available."""
    attributes: Dict[str, str] = {}

    sys_class_path = Path("/sys/class") / "video4linux" / devnode.name
    index_path = sys_class_path / "index"
    if index_path.exists():
        index_value = index_path.read_text(encoding="ascii").strip()
        if index_value:
            attributes["index"] = index_value

    return attributes


def choose_matchers(properties: Dict[str, str]) -> List[Tuple[str, str]]:
    preferred_keys: Sequence[str] = (
        "ID_SERIAL_SHORT",
        "ID_SERIAL",
        "ID_PATH",
    )

    matchers: List[Tuple[str, str]] = []
    for key in preferred_keys:
        value = properties.get(key)
        if value:
            matchers.append((f"ENV{{{key}}}", value))
            break

    vendor = properties.get("ID_VENDOR_ID")
    product = properties.get("ID_MODEL_ID")
    if vendor:
        matchers.append(("ENV{ID_VENDOR_ID}", vendor))
    if product:
        matchers.append(("ENV{ID_MODEL_ID}", product))

    if not matchers:
        raise ValueError(
            "No stable udev properties found. Expected one of ID_SERIAL_SHORT, "
            "ID_SERIAL, ID_PATH, ID_VENDOR_ID, or ID_MODEL_ID."
        )

    return matchers


def escape_rule_value(value: str) -> str:
    return value.replace('\\', r'\\').replace('"', r'\"')


def build_rule(spec: DeviceSpec, properties: Dict[str, str]) -> str:
    rule_parts = [f'SUBSYSTEM=="{spec.subsystem}"']
    for key, value in choose_matchers(properties):
        rule_parts.append(f'{key}=="{escape_rule_value(value)}"')

    if spec.subsystem == "video4linux":
        # Many UVC cameras expose multiple /dev/video* nodes. Restrict the
        # symlink to the actual capture interface so it doesn't drift onto a
        # metadata-only sibling node.
        v4l_caps = properties.get("ID_V4L_CAPABILITIES")
        if v4l_caps and ":capture:" in v4l_caps:
            rule_parts.append('ENV{ID_V4L_CAPABILITIES}=="*:capture:*"')

        index_value = query_sysfs_attributes(spec.devnode).get("index")
        if index_value is not None:
            rule_parts.append(f'ATTR{{index}}=="{escape_rule_value(index_value)}"')

    rule_parts.append(f'SYMLINK+="{spec.symlink}"')
    return ", ".join(rule_parts)


def build_rules_text(specs: Sequence[DeviceSpec]) -> str:
    lines: List[str] = list(HEADER)
    for spec in specs:
        properties = query_udev_properties(spec.devnode)
        lines.append(f"# {spec.label}: {spec.devnode}")
        lines.append(build_rule(spec, properties))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    args = parse_args()
    specs = list(iter_specs(args))
    if not specs:
        print(
            "No devices specified. Provide at least one of --camera, --motors, or --face.",
            file=sys.stderr,
        )
        return 2

    try:
        rules_text = build_rules_text(specs)
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if args.output:
        args.output.write_text(rules_text, encoding="ascii")
        print(f"Wrote {args.output}")
    else:
        print(rules_text, end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
